Add middy, json-shema-to-ts, architecture diagram to readme and rename ressources to make it more generic
theodo/S4 pull request #1
Opened 2020-10-14 15:30 UTC by trigaut

2020-11-30 18:38 UTC, fredericbarthelet commented on .gitignore
> +jspm_packages
jspm  packages  ?

2020-11-30 18:50 UTC, fredericbarthelet commented on README.md
> +yarn sls deploy --aws-profile=YOUR_AWS_PROFILE
il te faut aussi le
```
serverless create --template-url https://github.com/theodo/S4 --path myService
cd myService && serverless deploy
```

je pense que t'as pas besoin du `aws-profile` qui est une option propre à ton cas d'usage mais qui a plus sa place dans la doc de la commande `deploy` que dans ta documentation

2020-11-30 18:53 UTC, fredericbarthelet commented on functions/getSignedDownloadUrl/handler.ts
> +export const main = getSignedDownloadUrl;
t'utilise pas ta middleware stack ici ? Si c'est le cas, t'as pas besoin d'un fichier qui abstrait la configuration de middy, tu peux tout mettre sur `getSignedUploadUrl` je pense.

2020-11-30 19:00 UTC, fredericbarthelet commented on package.json
> +    "@types/serverless": "^1.78.1",
tu peux utiliser `@serverless/typescript` plutôt :)

2020-11-30 19:01 UTC, fredericbarthelet requested changes
Quelques petits commentaires, mais c'est cool ce que tu as fait sinon :)

2020-12-01 08:45 UTC, trigaut commented on functions/getSignedDownloadUrl/handler.ts
> +export const main = getSignedDownloadUrl;
C'est une lambda qui est censée être invoquée par une autre normalement

2020-12-01 09:27 UTC, trigaut commented on package.json
> +    "@types/serverless": "^1.78.1",
Mais comment on importe `import * as AwsConfig from "serverless/aws";` après ?

2020-12-01 09:30 UTC, trigaut commented on package.json
> +    "@types/serverless": "^1.78.1",
Il faudra changer beaucoup de chose au fichier serverless non ? Je fais ça dans une prochaine PR ?

2020-12-01 16:44 UTC, merged